"""new fields recipes and new tag model

Revision ID: 0006e9d5cf47
Revises: 2f15e7c515f4
Create Date: 2023-05-30 18:49:26.326625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006e9d5cf47'
down_revision = '2f15e7c515f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('preparation_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cooking_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(length=10000), nullable=True))
        batch_op.drop_column('servings')
        batch_op.drop_column('calories')
        batch_op.drop_column('cooking_time')
        batch_op.drop_column('preparation_time')
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
